// import type { FolderStructure } from '../types/project-types'

// export const defaultStructure: FolderStructure[] = [
//   {
//     id: 'proceso-licitacion',
//     name: 'Proceso de licitacion',
//     minDocuments: 3,
//     documents: [],
//     subfolders: [
//       {
//         id: 'bases-licitacion',
//         name: 'Bases de Licitación',
//         minDocuments: 2,
//         documents: [],
//         subfolders: [],
//         parentId: 'proceso-licitacion',
//       },
//       {
//         id: 'consultas-respuestas',
//         name: 'Consultas y Respuestas',
//         minDocuments: 1,
//         documents: [],
//         subfolders: [],
//         parentId: 'proceso-licitacion',
//       },
//     ],
//   },
//   {
//     id: 'proceso-adjudicacion',
//     name: 'Proceso de adjudicacion',
//     minDocuments: 3,
//     documents: [],
//     subfolders: [
//       {
//         id: 'evaluacion-ofertas',
//         name: 'Evaluación de Ofertas',
//         minDocuments: 2,
//         documents: [],
//         subfolders: [],
//         parentId: 'proceso-adjudicacion',
//       },
//       {
//         id: 'informes-tecnicos',
//         name: 'Informes Técnicos',
//         minDocuments: 1,
//         documents: [],
//         subfolders: [],
//         parentId: 'proceso-adjudicacion',
//       },
//     ],
//   },
//   {
//     id: 'ejecucion',
//     name: 'Ejecucion',
//     minDocuments: 3,
//     documents: [],
//     subfolders: [
//       {
//         id: 'contratos-convenios',
//         name: 'Contratos y Convenios',
//         minDocuments: 1,
//         documents: [],
//         subfolders: [],
//         parentId: 'ejecucion',
//       },
//       {
//         id: 'estados-pago',
//         name: 'Estados de Pago',
//         minDocuments: 2,
//         documents: [],
//         subfolders: [],
//         parentId: 'ejecucion',
//       },
//     ],
//   },
//   {
//     id: 'modificaciones-obras',
//     name: 'Modificacion de obras y convenios',
//     minDocuments: 2,
//     documents: [],
//     subfolders: [
//       {
//         id: 'solicitudes-modificacion',
//         name: 'Solicitudes de Modificación',
//         minDocuments: 1,
//         documents: [],
//         subfolders: [],
//         parentId: 'modificaciones-obras',
//       },
//       {
//         id: 'convenios-modificatorios',
//         name: 'Convenios Modificatorios',
//         minDocuments: 1,
//         documents: [],
//         subfolders: [],
//         parentId: 'modificaciones-obras',
//       },
//     ],
//   },
//   {
//     id: 'otros-documentos',
//     name: 'Otros documentos',
//     minDocuments: 1,
//     documents: [],
//     subfolders: [
//       {
//         id: 'documentacion-general',
//         name: 'Documentación General',
//         minDocuments: 1,
//         documents: [],
//         subfolders: [],
//         parentId: 'otros-documentos',
//       },
//     ],
//   },
//   {
//     id: 'informe-mensual',
//     name: 'Informe de estado mensual de la consecion',
//     minDocuments: 3,
//     documents: [],
//     subfolders: [
//       {
//         id: 'informes-avance',
//         name: 'Informes de Avance',
//         minDocuments: 1,
//         documents: [],
//         subfolders: [],
//         parentId: 'informe-mensual',
//       },
//       {
//         id: 'fotografias',
//         name: 'Fotografías',
//         minDocuments: 1,
//         documents: [],
//         subfolders: [],
//         parentId: 'informe-mensual',
//       },
//       {
//         id: 'indicadores',
//         name: 'Indicadores',
//         minDocuments: 1,
//         documents: [],
//         subfolders: [],
//         parentId: 'informe-mensual',
//       },
//     ],
//   },
// ]
